server:
  port: 8080

spring:
  application:
    name: mody-server-prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: classpath:application.yml

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

logging:
  level:
    root: INFO
    org.springframework: INFO
  config: classpath:logback-spring-mody.xml

sentry:
  enabled: true