server:
  port: 8000

spring:
  application:
    name: mody-server-dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    config:
      import: classpath:application.yml

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    root: INFO
    org.springframework: INFO
  config: classpath:logback-spring-mody.xml

sentry:
  enabled: true